- name: install packages to allow apt to use a repository over HTTPS
  apt:
    name: "{{item}}"
    update_cache: true
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: add docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: install docker-ce
  apt:
    name: docker-ce=19.03.1
    update_cache: yes

# deb模式
# - name: install docker-ce
  # apt:
  #   deb: https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_19.03.1~3-0~ubuntu-bionic_amd64.deb
